### PR TITLE
TypeName: add missing first level enum struct in front of the type

### PR DESCRIPTION
**Pull request by ArthurVasseur**

### CODE REVIEW

**Comment by SirLynix** [comment]
Thanks! Would you mind to add a unit test case for this as well?

**Comment by ArthurVasseur** [comment]
The unit test is already there : https://github.com/NazaraEngine/NazaraUtils/blob/b35b46944c15f7131263f0a53c11311f907414e8/tests/src/TypeNameTests.cpp#L12

**Comment by SirLynix** [comment]
But since that unit test passes without this change, this change has no impact?

**Comment by SirLynix** [comment]
I'm merging it in case MSVC makes the distinction in the future.

**Pull request merged**
